# Site settings
email: &#104;&#111;&#119;&#100;&#121;&#64;&#109;&#97;&#100;&#101;&#98;&#121;&#98;&#111;&#119;&#116;&#105;&#101;&#46;&#99;&#111;&#109;
description: > # this means to ignore newlines until "baseurl:"
  We're Bowtie. A two man strong app creation studio based in Stockholm.
  We strive for stunning graphics, awesome user experiences and classy code.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://madebybowtie.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude: [README.md, CNAME, Gemfile, Gemfile.lock]
